name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test on node v${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16, 18]
        os: [ubuntu-latest]
    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Linting
        run: yarn lint

      - name: Run TypeScript compiler
        run: yarn build:check

      - name: Run tests
        run: yarn test

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
