name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test on Node.js v20 (ubuntu-latest)
    runs-on: ubuntu-latest
    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Linting
        run: bun --bun run lint

      - name: Run TypeScript compiler
        run: bun --bun run build:check

      - name: Run tests
        run: bun run test

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
